/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tac_game_1;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author arjun
 */
public class Tic_Tac extends javax.swing.JFrame {

    int turn = 2;
    
    int buttonused [] = {0,0,0,0,0,0,0,0,0,};
    
    int p1won [] = {0,0,0,0,0,0,0,0,0,};
    int p2won [] = {0,0,0,0,0,0,0,0,0,};
    
    int p1won ()
    {
        if(p1won [0] == 1 && p1won [1] == 1 && p1won [2] == 1)
        {
            return 1;
        }
        
        if(p1won [3] == 1 && p1won [4] == 1 && p1won [5] == 1)
        {
            return 1;
        }
        
        if(p1won [6] == 1 && p1won [7] == 1 && p1won [8] == 1)
        {
            return 1;
        }
        
        if(p1won [1] == 1 && p1won [4] == 1 && p1won [7] == 1)
        {
            return 1;
        }
        
        if(p1won [2] == 1 && p1won [5] == 1 && p1won [8] == 1)
        {
            return 1;
        }
        
        if(p1won [2] == 1 && p1won [4] == 1 && p1won [6] == 1)
        {
            return 1;
        }
        
        if(p1won [0] == 1 && p1won [4] == 1 && p1won [8] == 1)
        {
            return 1;
        }
        
       return 0;
             
    }
    
    int p2won ()
    {
        if(p2won [0] == 1 && p2won [1] == 1 && p2won [2] == 1)
        {
            return 1;
        }
        
        if(p2won [3] == 1 && p2won [4] == 1 && p2won [5] == 1)
        {
            return 1;
        }
        
        if(p2won [6] == 1 && p2won [7] == 1 && p2won [8] == 1)
        {
            return 1;
        }
        
        if(p2won [1] == 1 && p2won [4] == 1 && p2won [7] == 1)
        {
            return 1;
        }
        
        if(p2won [2] == 1 && p2won [5] == 1 && p2won [8] == 1)
        {
            return 1;
        }
        
        if(p2won [2] == 1 && p2won [4] == 1 && p2won [6] == 1)
        {
            return 1;
        }
        
        if(p2won [0] == 1 && p2won [4] == 1 && p2won [8] == 1)
        {
            return 1;
        }
        
       return 0;
             
    }
    
    
    
    public Tic_Tac() {
        initComponents();
        setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Tic Tac toy Game");

        b1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        button.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        button.setText("Play Again");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
       b1.setText("");
       b2.setText("");
       b3.setText("");
       b4.setText("");
       b5.setText("");
       b6.setText("");
       b7.setText("");
       b8.setText("");
       b9.setText("");
       
       turn = 2;
       
       for(int i = 0; i<9; i++)
       {
           buttonused[i] = 0;
       }
       
       for(int i = 0; i<9; i++)
       {
           p1won[i] = 0;
       }
       
       for(int i = 0; i<9; i++)
       {
           p2won[i] = 0;
       }
       
    }//GEN-LAST:event_buttonActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if (buttonused [0] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b1.setText("X");
                buttonused [0] = 1;
                p1won [0] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b1.setText("O") ;
                buttonused [0] = 1;
                p2won [0] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
        if (buttonused [1] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b2.setText("X");
                buttonused [1] = 1;
                p1won [1] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b2.setText("O") ;
                buttonused [1] = 1;
                p2won [1] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
         if (buttonused [2] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b3.setText("X");
                buttonused [2] = 1;
                p1won [2] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b3.setText("O") ;
                buttonused [2] = 1;
                p2won [2] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        
        if (buttonused [3] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b6.setText("X");
                buttonused [3] = 1;
                p1won [3] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b6.setText("O") ;
                buttonused [3] = 1;
                p2won [2] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        
        if (buttonused [4] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b5.setText("X");
                buttonused [4] = 1;
                p1won [4] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b5.setText("O") ;
                buttonused [4] = 1;
                p2won [4] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        
        if (buttonused [5] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b4.setText("X");
                buttonused [5] = 1;
                p1won [5] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b4.setText("O") ;
                buttonused [5] = 1;
                p2won [5] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        
        if (buttonused [6] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b7.setText("X");
                buttonused [6] = 1;
                p1won [6] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b7.setText("O") ;
                buttonused [6] = 1;
                p2won [6] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
       
      if (buttonused [7] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b8.setText("X");
                buttonused [7] = 1;
                p1won [7] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b8.setText("O") ;
                buttonused [7] = 1;
                p2won [7] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
       
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        
       if (buttonused [8] ==0)
        {
            if (turn%2==0)
            {
                turn++;
                b9.setText("X");
                buttonused [8] = 1;
                p1won [8] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        
            else
            
            {
                turn++;
                b9.setText("O") ;
                buttonused [8] = 1;
                p2won [8] = 1;
                
                //*************Winning Logic***********
                int result1 = p1won();
                int result2 = p2won();
                
                if(result1 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player One Has Won**");
                }
                
                else if (result2 == 1)
                {
                    JOptionPane.showMessageDialog(rootPane, "** Player Two Has Won**");
                }
            }
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(rootPane, "This Button Is Allready Used !");
        }
       
    }//GEN-LAST:event_b9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tic_Tac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton button;
    // End of variables declaration//GEN-END:variables
}
